
[
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1713268552.407843,
        "hostOnly": false,
        "httpOnly": false,
        "name": "km_ai",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "getthingsperfect1213%40outlook.com"
    },
    {
        "domain": ".neilpatel.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "__hssrc",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1678710351,
        "hostOnly": false,
        "httpOnly": false,
        "name": "km_vs",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1678794959,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.2.1482873863.1678610639"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1703487649,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ttp",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "e426537a-fa52-4720-806e-3f88a18563d3"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1678708676,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_hjIncludedInSessionSample_2058125",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "0"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1684368000,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gaexp",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GAX1.2.Q8Wt-lqFSu6fzqNAwPK9IQ.19495.1"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1709342588,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ce.s",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "v~682904c99384503e172b8c179c44f8f86648e788~vpv~3"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1678710356,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_hjSession_2058125",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "eyJpZCI6IjE1MGJlNDQ4LTNhYmItNDg5ZS05YmZhLWM0MWMxNDVjMTYwOCIsImNyZWF0ZWQiOjE2Nzg3MDg1NTY4MDksImluU2FtcGxlIjpmYWxzZX0="
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1710244558,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_clck",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "bq8j3r|1|f9v|0"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1702185772.539704,
        "hostOnly": false,
        "httpOnly": false,
        "name": "km_lv",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "x"
    },
    {
        "domain": ".app.neilpatel.com",
        "expirationDate": 1678794944,
        "hostOnly": false,
        "httpOnly": false,
        "name": "id",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMGE4ZWUxYmYtYWZhNC00YzA5LWJkY2ItMjJmNmRkYWE4NzIxIiwiZXhwIjoxNjc4ODgwNjI5fQ.6RrEMKN15BwPx9KvLwPxGOaBuI_8B9hHg00QImDQuXQ"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1678794960,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_clsk",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "ogrgq4|1678708560020|1|1|w.clarity.ms/collect"
    },
    {
        "domain": "app.neilpatel.com",
        "expirationDate": 1681318558,
        "hostOnly": true,
        "httpOnly": false,
        "name": "1178_Ubersuggest_Pricing_Redesign",
        "path": "/en",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1694181692,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__hstc",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "240018588.2be50761d237d4cf4bdf381fe8050920.1677209607185.1678610640959.1678629688166.38"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1713268556.536474,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_6QNYJFNF1D",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS1.1.1678708556.13.0.1678708556.60.0.0"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1708531551,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__zlcmid",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1EXlcRZSceol2MO"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1686484559,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fbp",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "fb.1.1667462170306.1625941678"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1713268559.064692,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.2.1121306381.1667462174"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1678708619,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gat_UA-16137731-1",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1683759999,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1.1.1971929646.1675983999"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1710244556,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_hjSessionUser_2058125",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "eyJpZCI6IjNlMmJjZDQ5LTkyNDAtNWNiNi05NmNmLTM5MTUwYTUzZGUyNyIsImNyZWF0ZWQiOjE2Njc0NjIxNjQ4NDQsImV4aXN0aW5nIjp0cnVlfQ=="
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1703487649,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_tt_enable_cookie",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1678794955,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetsid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "0550ba00c0b211edb61cc74024089576"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1712404555,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetvid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "fda70310b3f311edaee2addd8c6a55e7"
    },
    {
        "domain": ".app.neilpatel.com",
        "expirationDate": 1710330954,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_vwo_uuid_v2",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "D3D3E2D733CFAF69BA005E54F15ABA973|66a2ac3a73e60f114c610719ea90aee8"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1713268552.407166,
        "hostOnly": false,
        "httpOnly": false,
        "name": "amp_276990",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "7NNaGInOd00ARdLOpt_Hr2.MGE4ZWUxYmYtYWZhNC00YzA5LWJkY2ItMjJmNmRkYWE4NzIx..1grdd7b5o.1grdd7b5o.2.0.2"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1694181692,
        "hostOnly": false,
        "httpOnly": false,
        "name": "hubspotutk",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "2be50761d237d4cf4bdf381fe8050920"
    },
    {
        "domain": ".neilpatel.com",
        "expirationDate": 1713268552.408001,
        "hostOnly": false,
        "httpOnly": false,
        "name": "km_ni",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "getthingsperfect1213%40outlook.com"
    },
    {
        "domain": ".neilpatel.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "kvcd",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "1678708551515"
    },
    {
        "domain": "app.neilpatel.com",
        "expirationDate": 1678794955,
        "hostOnly": true,
        "httpOnly": false,
        "name": "ln_or",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "eyIzOTExNDIwIjoiZCJ9"
    },
    {
        "domain": "app.neilpatel.com",
        "expirationDate": 1679819603,
        "hostOnly": true,
        "httpOnly": false,
        "name": "login_register_spz",
        "path": "/en",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1"
    }
]
